using System.Collections.Generic;

namespace SPWare.VirtualSoundCanvas.Localization
{
    /// <summary>한국어 문구 -> 영어 문구. 키에 {0}, {1} 자리표시가 있으면 템플릿으로 쓴다(Loc.T 참고).</summary>
    internal static class LocStrings
    {
        internal static readonly Dictionary<string, string> Table = new()
        {
            // ---- XAML (화면/툴팁/도움말) ----
            ["1. loopMIDI 같은 프로그램으로 가상 MIDI 포트를 하나 만듭니다.\n2. 설정 > MIDI 포트에서 그 포트를 \"가상 입력 포트\"로 고릅니다.\n3. 쓸 장치 탭(SPE3 / SPE5)을 열고 설정에서 ROM 폴더를 지정합니다.\n4. [시작]을 누른 뒤 게임이나 시퀀서의 MIDI 출력을 그 포트로 지정합니다.\n\"앱을 켜면 자동으로 시작\"에 체크하면 다음부터는 실행만 하면 됩니다."] = "1. Create a virtual MIDI port with a program such as loopMIDI.\n2. In Settings > MIDI port, choose that port as the \"virtual input port\".\n3. Open the device tab you want to use (SPE3 / SPE5) and set its ROM folder in Settings.\n4. Press [Start], then point your game's or sequencer's MIDI output at that port.\nIf you tick \"Start automatically when the app opens\", you only need to launch the app next time.",
            ["Language / 언어"] = "Language / 언어",
            ["MIDI 종류 (고르면 채널 배정과 기본 엔진이 한 번에 정해집니다)"] = "MIDI type (choosing one sets the channel assignment and the default engine at once)",
            ["MIDI 종류와 채널 배정"] = "MIDI type & channel assignment",
            ["MIDI 포트"] = "MIDI port",
            ["MT-32 ROM 세트"] = "MT-32 ROM set",
            ["SPE3 화면"] = "SPE3 panel",
            ["SPE3를 초기 상태로 리셋합니다(다른 게임의 음색/설정이 남아 소리가 다르게 들릴 때). 마스터 볼륨은 노브 값으로 다시 맞춥니다."] = "Resets SPE3 to its initial state (use it when sounds or settings left by another game make it sound different). The master volume is set back to the knob value.",
            ["SPE5 화면"] = "SPE5 panel",
            ["SC-55mkII ROM 폴더"] = "SC-55mkII ROM folder",
            ["※ Applies after restart / 다시 시작하면 적용됩니다."] = "※ Applies after restart / 다시 시작하면 적용됩니다.",
            ["※ 맨 위 탭은 화면에 어느 장치를 띄울지만 고릅니다(소리 경로와 무관). 실제 소리는 이 배정과 위의 기본 엔진으로 결정됩니다."] = "※ The tabs at the top only choose which device is shown on screen (they do not affect the sound path). The actual sound follows this assignment and the default engine above.",
            ["※ 시작 버튼을 눌러야 반영됩니다. 게임마다 요구하는 세트가 다를 수 있습니다(구형 MT-32 / 신형 MT-32 / CM-32L)."] = "※ Changes take effect when you press Start. Different games may need different sets (old MT-32 / new MT-32 / CM-32L).",
            ["※ 신호(게이지)는 움직이는데 소리만 안 날 때, 앱을 껐다 켜지 않고 오디오 출력만 다시 여는 버튼입니다."] = "※ Reopens only the audio output, without restarting the app, for when the meters move but there is no sound.",
            ["※ 이 폴더 안에 rom1.bin / rom2.bin / rom_sm.bin / waverom1.bin / waverom2.bin 이 있어야 합니다."] = "※ This folder must contain rom1.bin / rom2.bin / rom_sm.bin / waverom1.bin / waverom2.bin.",
            ["가상 입력 포트 (loopMIDI 등)"] = "Virtual input port (loopMIDI etc.)",
            ["도움말"] = "Help",
            ["들어오는 MIDI(GM On / GS Reset / SPE3 SysEx)를 보고 종류를 자동으로 바꾸기"] = "Switch the type automatically when incoming MIDI (GM On / GS Reset / SPE3 SysEx) is detected",
            ["리듬 파트 선택"] = "Select rhythm part",
            ["마스터"] = "Master",
            ["맨 위 탭(SPE3 / SPE5)은 화면에 어느 장치를 보여 줄지만 고릅니다. 소리가 어느 장치로 가는지는 설정의 채널 배정이 정합니다. 종료할 때 보던 탭, 창 위치와 크기, 접어 둔 설정 항목을 기억해서 다음 실행 때 그대로 엽니다. 앱은 한 번에 하나만 실행됩니다."] = "The tabs at the top (SPE3 / SPE5) only choose which device is shown. Which device the sound goes to is decided by the channel assignment in Settings. The app remembers the tab you were on, the window position and size, and which settings sections were collapsed, and restores them next time. Only one copy of the app runs at a time.",
            ["먼저 PART를 고른 뒤 누르면, 노브가 그 파트의 음량(0~100)을 조절합니다. 다시 누르면 노브가 SPE3 전체 음량으로 돌아갑니다."] = "Choose a PART first, then press this: the knob adjusts that part's volume (0–100). Press again to return the knob to the overall SPE3 volume.",
            ["배정"] = "Assign",
            ["배정하지 않은 채널의 기본 엔진"] = "Default engine for unassigned channels",
            ["볼륨은 세 종류"] = "Three kinds of volume",
            ["빠른 시작"] = "Quick start",
            ["상태"] = "Status",
            ["선택한 세트의 ROM 폴더"] = "ROM folder of the selected set",
            ["설정"] = "Settings",
            ["설정 > 오디오의 슬라이더(마스터, SPE3, SPE5)는 이 앱이 소리를 섞어 내보낼 때의 크기입니다. SPE3 화면의 노브는 SPE3 자체의 마스터 볼륨이라 슬라이더와 별개이고, SPE5 화면의 노브는 SPE5 슬라이더와 같은 값입니다."] = "The sliders under Settings > Audio (Master, SPE3, SPE5) set the level at which this app mixes the sound. The knob on the SPE3 panel is SPE3's own master volume, separate from the slider; the knob on the SPE5 panel has the same value as the SPE5 slider.",
            ["설정 아래쪽 \"상태\" 로그에서 ROM을 찾았는지, MIDI 포트가 열렸는지 먼저 확인하세요. ROM 폴더가 틀리면 \"건너뜀\" 메시지가 나옵니다. 그다음 [시작]을 눌렀는지, 게임의 MIDI 출력이 같은 가상 포트인지, 그 MIDI 채널이 원하는 엔진으로 배정돼 있는지 확인하세요. 화면의 게이지가 움직이는데 소리가 안 나면 먼저 마스터와 엔진별 볼륨 슬라이더를 보고, 그래도 안 나면 오디오 카드의 \"오디오 출력 다시 시작\" 버튼을 눌러 보세요(장치를 새로 엽니다)."] = "First check the \"Status\" log below Settings to see whether the ROMs were found and the MIDI port opened. If the ROM folder is wrong you will see a \"skipped\" message. Then make sure you pressed [Start], that your game's MIDI output goes to the same virtual port, and that the MIDI channel is assigned to the engine you want. If the meters move but there is no sound, check the Master and per-engine volume sliders first; if that doesn't help, press \"Restart audio output\" in the Audio card (it reopens the device).",
            ["소리가 안 날 때"] = "No sound?",
            ["시작"] = "Start",
            ["액정과 버튼은 에뮬레이터 펌웨어가 실제로 처리합니다. 버튼은 왼쪽 클릭 = 누르는 동안 눌림, 오른쪽 클릭 = 눌린 채로 고정(다시 오른쪽 클릭하면 해제), Shift+클릭 = 그 쌍의 ◀▶를 동시에 누름입니다. PART ◀▶로 파트를 고르면 LEVEL, PAN, REVERB, CHORUS, KEY SHIFT, INSTRUMENT, MIDI CH 조정이 그 파트에만 적용됩니다(파트 N = MIDI 채널 N, 파트 10 = 드럼). ALL은 전체 파트, MUTE는 음소거입니다. POWER를 누르면 대기 상태가 되고 다시 누르면 돌아옵니다. VOLUME 노브(1~100)는 SPE5 음량입니다. 게임이 프로그램 체인지나 CC를 보내면 패널에서 바꾼 값을 덮어씁니다. 액정 대비는 PART ◀▶ 동시 누름으로 설정 메뉴에 들어가 ALL/MUTE로 \"LCD Contrast\"를 고르고 INSTRUMENT ◀▶로 값을 바꾼 뒤 다시 PART ◀▶를 동시에 눌러 확정하며, 값은 저장됩니다."] = "The display and buttons are handled by the emulated firmware itself. Buttons: left click = pressed while held, right click = latched down (right-click again to release), Shift+click = press the ◀▶ pair at the same time. After choosing a part with PART ◀▶, LEVEL, PAN, REVERB, CHORUS, KEY SHIFT, INSTRUMENT and MIDI CH apply to that part only (part N = MIDI channel N, part 10 = drums). ALL is all parts, MUTE is mute. POWER puts the unit in standby and pressing it again wakes it. The VOLUME knob (1–100) is the SPE5 volume. When a game sends program changes or CCs they overwrite values set on the panel. To adjust the LCD contrast, press PART ◀▶ together to enter the settings menu, choose \"LCD Contrast\" with ALL/MUTE, change the value with INSTRUMENT ◀▶, then press PART ◀▶ together again to confirm; the value is saved.",
            ["액정은 엔진이 알려 주는 실기 LCD 글자 그대로입니다(파트 상태와 Vol). 오른쪽 SELECT/VOLUME 노브는 SPE3의 마스터 볼륨(1~100)입니다. 노브를 잡고 원을 그리듯 돌리거나 마우스 휠(한 칸에 2)로 조절하면 액정의 Vol 값도 같이 바뀌고, 게임이 볼륨 SysEx를 보내면 노브가 따라 돕니다. 값은 종료할 때 저장합니다. MIDI MESSAGE 램프는 MIDI를 받을 때 깜박입니다."] = "The display shows the original LCD text reported by the engine (part status and Vol). The SELECT/VOLUME knob on the right is the master volume of SPE3 (1–100). Grab the knob and turn it in a circle, or use the mouse wheel (2 per notch); the Vol value on the display changes with it, and if a game sends a volume SysEx the knob follows. The value is saved on exit. The MIDI MESSAGE lamp blinks when MIDI is received.",
            ["앱을 켜면 자동으로 시작"] = "Start automatically when the app opens",
            ["엔진"] = "Engine",
            ["오디오"] = "Audio",
            ["오디오 출력 다시 시작"] = "Restart audio output",
            ["직접 배정"] = "Manual assignment",
            ["찾아보기"] = "Browse",
            ["채널"] = "Channel",
            ["채널 배정 (0-15)"] = "Channel assignment (0-15)",
            ["채널 배정에서 MIDI 종류를 고르면 채널 배정과 기본 엔진이 한 번에 정해집니다. 자동 감지를 켜 두면 들어오는 GM On / GS Reset / SPE3 SysEx를 보고 종류를 알아서 바꿉니다. 직접 배정은 채널(0~15)마다 엔진을 따로 정하는 기능이고, 배정하지 않은 채널은 기본 엔진으로 갑니다. SPE3의 소리 파트는 MIDI 채널 2~9(리듬은 10, 1~16 기준)에 있으므로 SPE3로 들으려면 채널 1이 아니라 그쪽 채널을 쓰세요. 배정 화면의 채널 번호는 0~15 기준이라 한 칸씩 작습니다."] = "Choosing a MIDI type in Channel assignment sets the channel assignment and the default engine at once. With auto-detect on, the app switches the type by itself when it sees GM On / GS Reset / SPE3 SysEx. Manual assignment sets an engine per channel (0–15); unassigned channels go to the default engine. SPE3's sound parts are on MIDI channels 2–9 (rhythm on 10, counting 1–16), so to hear SPE3 use those channels rather than channel 1. Channel numbers on the assignment screen count 0–15, so they are one lower.",
            ["클릭: 누르기 / Shift+클릭: ◀ ▶ 동시에 / 오른쪽 클릭: 눌린 채로 고정(다시 오른쪽 클릭하면 해제)"] = "Click: press / Shift+click: press ◀ ▶ together / Right click: latch down (right-click again to release)",
            ["클릭: 전원 켜기/끄기(대기)"] = "Click: power on/off (standby)",
            ["파트 1 선택 (Shift+클릭 = 파트 6 - 실기는 MASTER VOLUME을 누른 채 누른다)"] = "Select part 1 (Shift+click = part 6; on the real unit you hold MASTER VOLUME while pressing)",
            ["파트 2 선택 (Shift+클릭 = 파트 7)"] = "Select part 2 (Shift+click = part 7)",
            ["파트 3 선택 (Shift+클릭 = 파트 8)"] = "Select part 3 (Shift+click = part 8)",
            ["파트 4 선택"] = "Select part 4",
            ["파트 5 선택"] = "Select part 5",
            ["화면과 탭"] = "Screen & tabs",
            // ---- 코드 (상태 로그, 콤보, 대화상자, 오류 메시지) ----
            ["SPE3 리셋"] = "SPE3 reset",
            ["구형 MT-32 (1987, v1.07)"] = "Old MT-32 (1987, v1.07)",
            ["신형 MT-32 (1988, patched)"] = "New MT-32 (1988, patched)",
            ["직접 설정"] = "Manual",
            ["SPE3 (MT-32 계열 게임 음악)"] = "SPE3 (MT-32-style game music)",
            ["GM · GS (SC-55 계열)"] = "GM · GS (SC-55-style)",
            ["저장된 채널 배정 {0}개를 불러왔습니다"] = "Loaded {0} saved channel assignment(s)",
            ["MIDI 장치 목록 조회 실패: {0}"] = "Failed to list MIDI devices: {0}",
            ["MT-32 / CM-32L ROM 폴더를 고르세요"] = "Choose the MT-32 / CM-32L ROM folder",
            ["SC-55mkII ROM 폴더를 고르세요"] = "Choose the SC-55mkII ROM folder",
            ["채널 {0} → {1} 배정"] = "Channel {0} → {1} assigned",
            ["MIDI 종류: 직접 설정 (채널 배정과 기본 엔진을 직접 관리합니다)"] = "MIDI type: Manual (you manage channel assignment and the default engine yourself)",
            ["MIDI 종류 자동 감지: {0} → 채널 배정을 자동으로 바꿨습니다"] = "MIDI type auto-detected: {0} → channel assignment changed automatically",
            ["MIDI 종류 '{0}' 적용 (개별 채널 배정 해제, 기본 엔진 변경)"] = "MIDI type '{0}' applied (per-channel assignments cleared, default engine changed)",
            ["SPE3 건너뜀: MT-32 ROM 폴더가 지정되지 않았습니다 (SPE3 탭에서 폴더를 고르세요)"] = "SPE3 skipped: no MT-32 ROM folder set (choose a folder on the SPE3 tab)",
            ["CONTROL과 PCM 둘 다"] = "both CONTROL and PCM",
            ["SPE3 건너뜀: MT-32 {0} ROM을 찾지 못했습니다. 지정한 폴더: {1}"] = "SPE3 skipped: MT-32 {0} ROM not found. Folder: {1}",
            ["MT-32 ROM 발견 - CONTROL: {0}, PCM: {1}"] = "MT-32 ROMs found - CONTROL: {0}, PCM: {1}",
            ["SPE3 엔진 초기화 완료 ({0}) - {1}"] = "SPE3 engine ready ({0}) - {1}",
            ["이전에 재생 중이던 곡 설정을 이어받았습니다 (SPE3)"] = "Picked up the song setup that was playing before (SPE3)",
            ["이전에 재생 중이던 곡 설정을 이어받았습니다 (SPE5)"] = "Picked up the song setup that was playing before (SPE5)",
            ["  └ 참고: 실기는 기본 상태에서 MIDI 채널 1번(0-based 0)에 파트가 배정되어 있지 않습니다. 채널 2번 이상으로 테스트해보세요."] = "  └ Note: the real unit has no part assigned to MIDI channel 1 (0-based 0) by default. Test with channel 2 or higher.",
            ["SPE3 초기화 실패: mt32_wrap.dll을 찾을 수 없습니다. 직접 빌드한 DLL을 exe와 같은 폴더(또는 Native\\x64\\)에 넣어주세요."] = "SPE3 init failed: mt32_wrap.dll not found. Put the DLL in the same folder as the exe (or in Native\\x64\\).",
            ["SPE3 초기화 실패: {0}"] = "SPE3 init failed: {0}",
            ["  └ {0}: 없음 (!)"] = "  └ {0}: missing (!)",
            ["크기 불일치! 표준 {0}바이트"] = "size mismatch! expected {0} bytes",
            ["  └ {0}: {1}바이트 - {2}"] = "  └ {0}: {1} bytes - {2}",
            ["  └ 그 폴더는 비어 있습니다: {0}"] = "  └ That folder is empty: {0}",
            ["  └ 그 폴더에 있는 파일: {0}"] = "  └ Files in that folder: {0}",
            ["  └ 폴더를 읽지 못했습니다: {0}"] = "  └ Could not read the folder: {0}",
            ["SPE5 건너뜀: SC-55mkII ROM 폴더가 지정되지 않았습니다 (SPE5 탭에서 폴더를 고르세요)"] = "SPE5 skipped: no SC-55mkII ROM folder set (choose a folder on the SPE5 tab)",
            ["  └ SPE5 펌웨어 부팅 중... (몇 초 걸립니다)"] = "  └ Booting SPE5 firmware... (takes a few seconds)",
            ["SPE5 엔진 초기화 완료 - {0}"] = "SPE5 engine ready - {0}",
            ["  └ SPE5 LCD 대비 {0} 복원"] = "  └ SPE5 LCD contrast {0} restored",
            ["SPE5 초기화 실패: nuked_sc55_wrap.dll을 찾을 수 없습니다. 빌드한 DLL을 exe와 같은 폴더(또는 Native\\x64\\)에 넣어주세요."] = "SPE5 init failed: nuked_sc55_wrap.dll not found. Put the DLL in the same folder as the exe (or in Native\\x64\\).",
            ["SPE5 초기화 실패: {0}"] = "SPE5 init failed: {0}",
            ["  └ 기본 재생 장치: {0}"] = "  └ Default playback device: {0}",
            ["  └ 기본 재생 장치를 확인하지 못했습니다: {0}"] = "  └ Could not determine the default playback device: {0}",
            ["오디오 출력 시작"] = "Audio output started",
            ["오디오 출력 시작 실패: {0}"] = "Failed to start audio output: {0}",
            ["기존 오디오 출력 정리 중 오류(무시하고 계속): {0}"] = "Error while cleaning up the old audio output (ignored, continuing): {0}",
            ["가상 입력 포트가 선택되지 않았습니다. loopMIDI 등을 설치 후 다시 실행하세요."] = "No virtual input port is selected. Install loopMIDI or similar and run again.",
            ["가상 MIDI 입력 연결 완료 - 대기 중 (SysEx 포함)"] = "Virtual MIDI input connected - waiting (SysEx included)",
            ["MIDI 입력 연결 실패: {0}"] = "Failed to connect the MIDI input: {0}",
            ["SPE5 ROM 파일이 없습니다: {0} (경로: {1})"] = "SPE5 ROM files missing: {0} (path: {1})",
            ["SPE5 ROM 로드 실패 - {0} (경로: {1})"] = "SPE5 ROM load failed - {0} (path: {1})",
            ["SPE3 ROM 로드 실패 - {0} (CONTROL: {1}, PCM: {2})"] = "SPE3 ROM load failed - {0} (CONTROL: {1}, PCM: {2})",
            ["원인 불명"] = "unknown cause",
            ["midiInOpen 실패 (코드 {0}) - 장치 인덱스 {1}"] = "midiInOpen failed (code {0}) - device index {1}",
            ["midiOutOpen 실패 (코드 {0}) - 장치 인덱스 {1}"] = "midiOutOpen failed (code {0}) - device index {1}",
            ["오류가 발생했습니다.\n\n{0}\n\n자세한 내용:\n{1}"] = "An error occurred.\n\n{0}\n\nDetails:\n{1}",
        };
    }
}
